# Generated by Django 5.1 on 2025-02-02 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha', 'matricula']},
        ),
    ]
