# Generated by Django 5.1 on 2025-01-22 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_matricula', models.CharField(max_length=10, null=True, unique=True)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.estudiante')),
            ],
            options={
                'unique_together': {('estudiante',)},
            },
        ),
        migrations.CreateModel(
            name='DetalleMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True)),
                ('matricula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detallematricula_set', to='students.matricula')),
            ],
            options={
                'unique_together': {('matricula',)},
            },
        ),
    ]
