# Generated by Django 5.1 on 2025-01-20 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('subjects', '0002_academicperiod_activitytemplate_activity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='behaviorsummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='behavior',
            name='academic_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subjects.academicperiod', verbose_name='Período Académico'),
        ),
        migrations.AddField(
            model_name='behaviorsummary',
            name='academic_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subjects.academicperiod'),
        ),
        migrations.AlterUniqueTogether(
            name='behaviorsummary',
            unique_together={('student', 'academic_period')},
        ),
    ]
