# Generated by Django 5.1 on 2025-01-29 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_detallematricula_unique_together_and_more'),
        ('subjects', '0012_asignacionprofesortrimestre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMatriculaTrimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_trimestre', to='students.detallematricula')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.trimestre')),
            ],
            options={
                'unique_together': {('detalle_matricula', 'trimestre')},
            },
        ),
        migrations.AddField(
            model_name='detallematricula',
            name='trimestres',
            field=models.ManyToManyField(through='students.DetalleMatriculaTrimestre', to='subjects.trimestre'),
        ),
    ]
