# Generated by Django 5.1 on 2025-01-22 17:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_detallematricula_unique_together_and_more'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromedioAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_p1', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('promedio_p2', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('promedio_p3', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('promedio_final', models.DecimalField(decimal_places=2, editable=False, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('detalle_matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.detallematricula')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcial', models.IntegerField(choices=[(1, 'Primer Parcial'), (2, 'Segundo Parcial'), (3, 'Tercer Parcial')], default=1)),
                ('tarea1', models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('tarea2', models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('tarea3', models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('tarea4', models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('examen', models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('promedio_final', models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('asignacion_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.asignacionprofesor')),
                ('detalle_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.detallematricula')),
            ],
            options={
                'unique_together': {('detalle_matricula', 'asignacion_profesor', 'parcial')},
            },
        ),
    ]
