# Generated by Django 5.1 on 2025-01-29 02:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_remove_promedioanual_promedio_p3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número del trimestre (1-3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trimestres', to='subjects.periodoacademico')),
            ],
            options={
                'ordering': ['periodo_academico', 'numero'],
                'unique_together': {('periodo_academico', 'numero')},
            },
        ),
    ]
