# Generated by Django 5.1 on 2025-01-29 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_alter_materia_options_trimestre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignacionprofesor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asignacionprofesor',
            name='trimestre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.trimestre'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionprofesor',
            unique_together={('profesor', 'materia', 'curso', 'periodo', 'trimestre')},
        ),
    ]
