# Generated by Django 5.1 on 2025-01-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_alter_periodoacademico_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodoacademico',
            options={},
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Trimestre',
        ),
    ]
