# Generated by Django 5.1 on 2025-01-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_trimestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='periodo',
        ),
        migrations.AddField(
            model_name='curso',
            name='trimestres',
            field=models.ManyToManyField(blank=True, to='subjects.trimestre'),
        ),
    ]
