# Generated by Django 5.1 on 2025-01-29 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_remove_curso_periodo_curso_trimestres'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='subjects.periodoacademico'),
        ),
    ]
