# Generated by Django 5.1 on 2025-01-29 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_curso_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionProfesorTrimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_trimestre', to='subjects.asignacionprofesor')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.trimestre')),
            ],
            options={
                'unique_together': {('asignacion', 'trimestre')},
            },
        ),
        migrations.AddField(
            model_name='asignacionprofesor',
            name='trimestres',
            field=models.ManyToManyField(through='subjects.AsignacionProfesorTrimestre', to='subjects.trimestre'),
        ),
    ]
