# Generated by Django 5.1 on 2025-01-29 05:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_detallematriculatrimestre_and_more'),
        ('subjects', '0012_asignacionprofesortrimestre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promedioanual',
            old_name='promedio_p2',
            new_name='promedio_t1',
        ),
        migrations.RenameField(
            model_name='promedioanual',
            old_name='promedio_p1',
            new_name='promedio_t2',
        ),
        migrations.AddField(
            model_name='promedioanual',
            name='promedio_t3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='promedioanual',
            name='promedio_final',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.CreateModel(
            name='Parcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(choices=[(1, 'Primer Parcial'), (2, 'Segundo Parcial')])),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parciales', to='subjects.trimestre')),
            ],
            options={
                'unique_together': {('trimestre', 'numero')},
            },
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='parcial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.parcial'),
        ),
        migrations.CreateModel(
            name='PromedioTrimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_p1', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('promedio_p2', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('examen_trimestral', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('promedio_final', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('detalle_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.detallematricula')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.trimestre')),
            ],
            options={
                'unique_together': {('detalle_matricula', 'trimestre')},
            },
        ),
    ]
