# Generated by Django 5.1 on 2025-01-29 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0013_rename_promedio_p2_promedioanual_promedio_t1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='parcial',
            field=models.IntegerField(choices=[(1, 'Primer Parcial'), (2, 'Segundo Parcial')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='promediotrimestre',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='promediotrimestre',
            name='detalle_matricula',
        ),
        migrations.RemoveField(
            model_name='promediotrimestre',
            name='trimestre',
        ),
        migrations.RenameField(
            model_name='promedioanual',
            old_name='promedio_t1',
            new_name='promedio_p1',
        ),
        migrations.RenameField(
            model_name='promedioanual',
            old_name='promedio_t2',
            new_name='promedio_p2',
        ),
        migrations.RemoveField(
            model_name='promedioanual',
            name='promedio_t3',
        ),
        migrations.AlterField(
            model_name='promedioanual',
            name='promedio_final',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.DeleteModel(
            name='Parcial',
        ),
        migrations.DeleteModel(
            name='PromedioTrimestre',
        ),
    ]
